// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pruhplqrmepvrbkzdomx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBydWhwbHFybWVwdnJia3pkb214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjE2MzMsImV4cCI6MjA2NjUzNzYzM30.kO5iTnYmDiPfrPFkpr3Bt8KBB0fbrM9DW1aIR_9X_WQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);